version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: clientes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"  # Porta 3308 externa mapeada para a 3306 do MySQL no container
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  clientes-service:
    image: clientes-service:latest
    container_name: clientes-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"  # Porta 8090 externa
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/clientes
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql-db
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
